[workspace]
authors = ["Raymond Tay <raymondtay1974@gmail.com>"]
channels = [
  "https://conda.modular.com/max",
  "conda-forge",
  "https://repo.prefix.dev/modular-community",
]
name = "mojo-journey"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25,<0.27"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
numpy = ">=2.3.5,<3"
emberjson = ">=0.2.1,<0.3"
