[workspace]
authors = ["Raymond Tay <raymondtay1974@gmail.com>"]
channels = [
  "https://conda.modular.com/max-nightly",
  "conda-forge",
  "https://repo.prefix.dev/modular-community",
]
name = "mojo-journey"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026022005,<0.27"
numpy = ">=2.3.5,<3"
emberjson = ">=0.3.0,<0.4"
numba = ">=0.63.1,<0.64"
